<#import "partials/main.ftlh" as main />

<@main.renderWith scripts=["/js/messages.js"] styles=[]>

    <div class="container" style="padding: 10px">
        <div class="list-group justify-content-center w-50 mx-auto">
            <a href="#" class="list-group-item list-group-item-action list-group-item-dark">
                List Of Chats
            </a>
        </div>
    </div>

</@main.renderWith>